In [1]:
import numpy as np
array=np.random.randint(1,100,9)
array

array([19, 10, 99, 13, 47, 27, 59,  4, 57], dtype=int32)

In [2]:
np.sqrt(array)

array([4.35889894, 3.16227766, 9.94987437, 3.60555128, 6.8556546 ,
       5.19615242, 7.68114575, 2.        , 7.54983444])

In [3]:
array.ndim

1

In [5]:
new_array=array.reshape(3,3)
new_array

array([[19, 10, 99],
       [13, 47, 27],
       [59,  4, 57]], dtype=int32)

In [6]:
new_array.ndim

2

In [7]:
new_array.ravel()

array([19, 10, 99, 13, 47, 27, 59,  4, 57], dtype=int32)

In [9]:
newm=new_array.reshape(3,3)
newm

array([[19, 10, 99],
       [13, 47, 27],
       [59,  4, 57]], dtype=int32)

In [10]:
newm[2,1:3]

array([ 4, 57], dtype=int32)

In [11]:
newm[1:2,1:3]

array([[47, 27]], dtype=int32)

In [12]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int32)

In [13]:
new_array[0:2,0:1]

array([[19],
       [13]], dtype=int32)

In [14]:
new_array[0:3,0:1]

array([[19],
       [13],
       [59]], dtype=int32)

In [15]:
new_array[1:3]

array([[13, 47, 27],
       [59,  4, 57]], dtype=int32)